install.packages("ggiraphExtra") 
library(ggiraphExtra)
str(USArrests)
head(USArrests)
library(tibble)
crime <- rownames_to_column(USArrests, var = "state")
crime$state <- tolower(crime$state) #주 이름을 모두 소문자로 바꾸기
str(crime)
library(ggplot2) 
install.packages("maps")
library(maps) 
install.packages("mapproj")
library(mapproj) 
states_map <- map_data("state") 
str(states_map)