install.packages("plotly") 
library(plotly)
library(ggplot2) 
p <- ggplot(data = mpg, aes(x = displ, y = hwy, col = drv)) + geom_point()
ggplotly(p)
p <- ggplot(data = diamonds, aes(x = cut, fill = clarity)) + geom_bar(position = "dodge") 
ggplotly(p)
ggplotly(ggplot(data = diamonds, aes(x = cut, fill = clarity)) + geom_bar(position = "dodge"))
install.packages("dygraphs") 
library(dygraphs)
economics <- ggplot2::economics 
head(economics)