library(xts) 
eco <- xts(economics$unemploy, order.by = economics$date) 
head(eco)
dygraph(eco)
dygraph(eco) %>% dyRangeSelector()
eco_a <- xts(economics$psavert, order.by = economics$date)
eco_b <- xts(economics$unemploy/1000, order.by = economics$date)
eco2 <- cbind(eco_a, eco_b) 
colnames(eco2) <- c("psavert", "unemploy") 
head(eco2)
dygraph(eco2) %>% dyRangeSelector() 